// Session.swift
// TennisContact — iOS
//
// CoreData Session entity.
// Schema defined in Resources/TennisContact.xcdatamodeld.
//
// Attributes:
//   date:              Date
//   videoFilename:     String
//   durationSeconds:   Double
//   consistencyScore:  Double
//   shots:             Set<Shot>   (to-many, cascade delete)
//
// See docs/architecture.md Data Models and Task 12

import Foundation
import CoreData

// NSManagedObject subclass is auto-generated by CoreData (codegen = Class Definition).
// Add custom helpers here as needed in Task 12.
