// Shot.swift
// TennisContact — iOS
//
// CoreData Shot entity.
// Schema defined in Resources/TennisContact.xcdatamodeld.
//
// Attributes:
//   timestamp:       Double   — seconds from video start
//   frameIndex:      Int64
//   forwardCm:       Double   — wrist.X - pelvis.X (positive = in front)
//   lateralCm:       Double   — wrist.Y - pelvis.Y (positive = toward dominant side)
//   heightCm:        Double   — wrist.Z in cm
//   velocityCmS:     Double   — wrist velocity at contact (cm/s)
//   classification:  String   — "early" | "optimal" | "late"
//   jointData:       Data     — archived [String: simd_float3] joint positions
//   session:         Session  — inverse relationship
//
// See docs/architecture.md Data Models and Task 12

import Foundation
import CoreData

// NSManagedObject subclass is auto-generated by CoreData (codegen = Class Definition).
// Add custom helpers here as needed in Task 12.
